- hosts: bastion
  become: true
  tasks:
    - name: Install security tools
      apt:
        name: [ufw, fail2ban, htop, vim]
        state: present
    
    - name: Configure UFW
      ufw:
        rule: allow
        port: '22'
        proto: tcp
    
    - name: Enable UFW
      ufw:
        state: enabled