- hosts: cicd
  become: true
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Ensure Jenkins GPG key is downloaded
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.gpg
        mode: '0644'
        force: yes  # Toujours écraser si la clé change

    - name: Ensure Jenkins repository is added
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache after adding Jenkins repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is started and enabled
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true

